<a href="https://colab.research.google.com/github/tapokVozmezdia/DBMS_project/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Untitled21_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import preprocessing
import numpy as np
import random
import pandas as pd
import math

In [ ]:
ar = np.zeros([8, 8])
ar[1::2,::2] = 1
ar[::2,1::2] = 1
print(ar)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
ar =  np.array([np.arange(0,5) for i in range(0,5)])
print(ar)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
ar = np.array([[[random.randint(0,101) for i in range(0,3)] for j in range(0,3)] for k in range(0,3)])
print(ar)

[[[ 6 68 64]
  [51 66 40]
  [36 69  2]]

 [[49 81 67]
  [63 13 26]
  [37 55 76]]

 [[84 99 64]
  [68 69 81]
  [55 29 31]]]


In [ ]:
size = random.randint(3, 8)
ar = np.array([[(1 if i % size == 0 or i == size - 1 or j == size - 1 or j % size == 0 else 0) for i in range(0, size)] for j in range(0, size)])
print(ar)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
ar = np.array([random.randint(0, 101) for i in range(0, 10)])
ar = np.sort(ar)
ar = ar[::-1]
print(ar)

[98 86 69 54 33 32 19 10  7  4]


In [ ]:
ar = np.array([[random.randint(0, 101) for i in range(0, 5)] for j in range(0,3)])
print(ar)
print(ar.shape, ", ", ar.size, ", ", ar.ndim)

[[79 64 43 88 11]
 [71 33 39 48 39]
 [35 58  6 33 44]]
(3, 5) ,  15 ,  2


In [ ]:
dot1 = tuple([random.randint(-100, 100)/10 for i in range(0,3)])
dot2 = tuple([random.randint(-100, 100)/10 for i in range(0,3)])
print(dot1, dot2)
r = math.sqrt((dot1[0] - dot2[0]) ** 2 + (dot1[1] - dot2[1]) ** 2 + (dot1[2] - dot2[2]) ** 2)
print(r)

(-6.1, -2.2, -3.5) (6.7, -6.7, -3.1)
13.573871960498229


In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male              40   
1    Exec-managerial        Husband  White    Male              13   
2  Handlers-cleaners  Not-in-family  White    Male              40   
3  Handlers-cleaners        Husband  Other    Male              40   
4     Prof-specialty           Wife  Other  Female              40   

  native_country  capital income_status  
0  United-States     2174         <=50K  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K  
4          Other        0         <=50K

In [ ]:
#print(dataframe.head(2))
#print(dataframe.tail(3))
#print(dataframe.shape)
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [ ]:
dataframe.iloc[3:11]

age         workclass  education_num         marital_status  \
3    53           Private              7     Married-civ-spouse   
4    28           Private             13     Married-civ-spouse   
5    37           Private             14     Married-civ-spouse   
6    49           Private              5  Married-spouse-absent   
7    52  Self-emp-not-inc              9     Married-civ-spouse   
8    31           Private             14          Never-married   
9    42           Private             13     Married-civ-spouse   
10   37           Private             10     Married-civ-spouse   

           occupation   relationship   race  gender  hours_per_week  \
3   Handlers-cleaners        Husband  Other    Male              40   
4      Prof-specialty           Wife  Other  Female              40   
5     Exec-managerial           Wife  White  Female              40   
6       Other-service  Not-in-family  Other  Female              16   
7     Exec-managerial        Husband  White    Male              45   
8      Prof-specialty  Not-in-family  White  Female              50   
9     Exec-managerial        Husband  White    Male              40   
10    Exec-managerial        Husband  Other    Male              80   

   native_country  capital income_status  
3   United-States        0         <=50K  
4           Other        0         <=50K  
5   United-States        0         <=50K  
6           Other        0         <=50K  
7   United-States        0          >50K  
8   United-States    14084          >50K  
9   United-States     5178          >50K  
10  United-States        0          >50K

In [ ]:
dataframe[dataframe['workclass'] == 'Private'].head(2)

age workclass  education_num      marital_status         occupation  \
2   38   Private              9            Divorced  Handlers-cleaners   
3   53   Private              7  Married-civ-spouse  Handlers-cleaners   

    relationship   race gender  hours_per_week native_country  capital  \
2  Not-in-family  White   Male              40  United-States        0   
3        Husband  Other   Male              40  United-States        0   

  income_status  
2         <=50K  
3         <=50K

In [ ]:
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)
col = dataframe['sepal_length_cm']
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
ar = np.array([[i] for i in col])
#print(ar)
scaled_feature = minmax_scale.fit_transform(ar) #min max
col2 = dataframe['sepal_width_cm']
ar2 = np.array([[i] for i in col2])
ans = preprocessing.MinMaxScaler().fit_transform(ar2)

array([[0.625     ],
       [0.41666667],
       [0.5       ],
       [0.45833333],
       [0.66666667],
       [0.79166667],
       [0.58333333],
       [0.58333333],
       [0.375     ],
       [0.45833333],
       [0.70833333],
       [0.58333333],
       [0.41666667],
       [0.41666667],
       [0.83333333],
       [1.        ],
       [0.79166667],
       [0.625     ],
       [0.75      ],
       [0.75      ],
       [0.58333333],
       [0.70833333],
       [0.66666667],
       [0.54166667],
       [0.58333333],
       [0.41666667],
       [0.58333333],
       [0.625     ],
       [0.58333333],
       [0.5       ],
       [0.45833333],
       [0.58333333],
       [0.875     ],
       [0.91666667],
       [0.45833333],
       [0.5       ],
       [0.625     ],
       [0.45833333],
       [0.41666667],
       [0.58333333],
       [0.625     ],
       [0.125     ],
       [0.5       ],
       [0.625     ],
       [0.75      ],
       [0.41666667],
       [0.75      ],
       [0.5  